// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4il6nTMkJOzIsGxcEmf6ZcLmrqCiV6_Q',
    appId: '1:1020001141699:web:7d7c216b8e7eac622cb376',
    messagingSenderId: '1020001141699',
    projectId: 'app-dev-safestefs',
    authDomain: 'app-dev-safestefs.firebaseapp.com',
    databaseURL:
        'https://app-dev-safestefs-default-rtdb.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'app-dev-safestefs.firebasestorage.app',
    measurementId: 'G-77YFQHZERT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3EJGUq473UEeJm5j8EheZqR763bFv0o',
    appId: '1:1020001141699:android:b508655be5f089c12cb376',
    messagingSenderId: '1020001141699',
    projectId: 'app-dev-safestefs',
    storageBucket: 'app-dev-safestefs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOm8tR5zUREoLPIGnhfhvwBJk8KqvX7IM',
    appId: '1:1020001141699:ios:748fa293a1d74c382cb376',
    messagingSenderId: '1020001141699',
    projectId: 'app-dev-safestefs',
    storageBucket: 'app-dev-safestefs.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOm8tR5zUREoLPIGnhfhvwBJk8KqvX7IM',
    appId: '1:1020001141699:ios:748fa293a1d74c382cb376',
    messagingSenderId: '1020001141699',
    projectId: 'app-dev-safestefs',
    storageBucket: 'app-dev-safestefs.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4il6nTMkJOzIsGxcEmf6ZcLmrqCiV6_Q',
    appId: '1:1020001141699:web:95d73a2add4637c52cb376',
    messagingSenderId: '1020001141699',
    projectId: 'app-dev-safestefs',
    authDomain: 'app-dev-safestefs.firebaseapp.com',
    storageBucket: 'app-dev-safestefs.firebasestorage.app',
    measurementId: 'G-2XFS2SS2XE',
  );
}
