import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // We need this to initialize Firebase
import 'firebase_options.dart'; // This file will be generated by the FlutterFire CLI

import 'screens/home_screen.dart';
import 'constants/app_colors.dart';
import 'screens/login_screen.dart';
import 'screens/register_screen.dart';

void main() async {
  // 1. Ensure Flutter's engine is fully initialized before we interact with native code (Firebase)
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 3. Run the app
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'GyroStep - Fall Detection System',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: ColorScheme.fromSeed(
          seedColor: AppColors.primary,
          brightness: Brightness.light,
        ),
        fontFamily: 'Roboto',
      ),
      home: const LoginScreen(),
    );
  }
}
